[package]
name = "vtrans"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "VTrans desktop application"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
vtrans-app = { workspace = true }
vtrans-core = { workspace = true }
tauri = { version = "2", features = ["tray-icon"] }
tokio = { workspace = true }
tracing = { workspace = true }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[lints]
workspace = true
